---
version: "3.7"

services:
  app:
    build:
      context: .
      target: base
    tty: true
    environment:
      PG_HOST: db
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tovala
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
